### ISSUE TITLE
Uncaught TypeError: refresh.refreshApiCallback(...).then is not a function

### ISSUE THREAD

**Issue by chrisbekas** [react-auth-kit/react-auth-kit#1025]
**Describe the bug**
The create-react-app-refresh-token example project shows

`Uncaught TypeError: refresh.refreshApiCallback(...).then is not a function `

Whenever the refreshApi function is invoked to refresh the token.

**Comment by D-Johnson89** [comment]
I'm having the same issue, and was wondering as I look through the documentation, I'm only seeing a way to set minute update intervals for the refreshApi. Can we set this up to update when invoked or set to time, depending on the needs of the application?
