### ISSUE TITLE
Use maybe docusaurus for docs

### ISSUE THREAD

**Issue by nicolad** [react-auth-kit/react-auth-kit#1069]
There is no dark mode in current docs.
[Docusaurus](https://docusaurus.io/) already has dark mode integrated along with other features.
It's markdown-based, so it shouldn't be complicated to migrate.

**Comment by darkmatter18** [comment]
@nicolad That's a great choice. We'll surely take that

**Comment by adi-uchiha** [comment]
Hey there, I want to work on this 

- [ ] Migrate the docs to use https://docusaurus.io/ 
- [ ] Give a option for dark mode

**Comment by 0xSooki** [comment]
Haii, I would love to work on this issue, if it's still up for grabs

**Comment by adi-uchiha** [comment]
This issue requires to initalise docusurus in a the _docs_ directory. 
This directory will contain a seperate _package.json docusaurus.config.js_
https://docusaurus.io/docs/installation#project-structure
Should I proceed ?

**Comment by darkmatter18** [comment]
@adi-uchiha Assigned you

**Comment by nicolad** [comment]
@adi-uchiha go for it

**Comment by adi-uchiha** [comment]
@darkmatter18 do I need to change the commit messages?

**Comment by darkmatter18** [comment]
@adi-uchiha Yes, we have to change

**Comment by adi-uchiha** [comment]
@darkmatter18 All good now I think

**Comment by nicolad** [comment]
@darkmatter18 please review the PR

https://github.com/react-auth-kit/react-auth-kit/pull/1083
