### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#1070]
<p align="center">
<img width="576" alt="Hfest-Logo-2-Color-Manga@2x" src="https://user-images.githubusercontent.com/30409045/190916995-f911e151-6514-4701-b046-6746f574741b.png">
</p>

<p align="center">
    <i>
        <b> React Auth Kit </b> welcomes everyone in Hacktoberfest 2022 </br>
       We are participating in Hacktoberfest 2022.
    </i>
</p>

<p align="center">
Start your contributing journey with React Auth Kit and get Swags from Hacktoberfest. You need only 4 pull requests.
</p>

### This issue will contain all the issues and Roadmap.

You can solve the issues by making the Pull Requests.

If you think that, we missed any issues then add your own issues as well.

## Issues

#1069, #1059

## Before you contribute

- Please go through the [CONTRUBUTING](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md) and respect the [CODE of CONDUCT](https://github.com/react-auth-kit/react-auth-kit/blob/master/CODE_OF_CONDUCT.md).

- Try to write the code and documentation as best as possible. 

**We give respect to all our Contributors. We also add them to our _Hall of Fame_.**

**Comment by LeviJunior21** [comment]
hacktoberfest

**Comment by LeviJunior21** [comment]
oi

**Comment by Omkar0803** [comment]
I would like to contribute

**Comment by Rishabh-14** [comment]
I would like to contribute
