### ISSUE TITLE
Improve and add more issue templates

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#1072]
# Problem

- The current issue templetes do not support all kinds of issues.

# Solution and Task

- Add the following type of `ISSUE TEMPLATES`
- Add them in `.github/ISSUE_TEMPLATE/` directory.

# Templates

1. Documentation Issue
2. Unexpected behaviors
3. Report a security vulnerability
4. How-To / All Other Questions

**Comment by adi-uchiha** [comment]
I want to work on this issue. Please assign me

**Comment by darkmatter18** [comment]
@adi-uchiha Assigned you
