### ISSUE TITLE
useAuthUser

### ISSUE THREAD

**Issue by avmentzer** [react-auth-kit/react-auth-kit#1076]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** \
I'm trying to get the UserState from the Context Provider with this function:
https://authkit.arkadip.dev/authdata/, but the variable stays undefinied. 

**Additional context**
What works is implementing the auth-kit and the private Route. Also checking if the user is authenticated with  useIsAuthenticated() works fine. 

The goal is to get the current email of the logged-in user and only allow the "admin" to do special operations.

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by darkmatter18** [comment]
Please provide the codebase or git repo link for a local test

**Comment by Kretiss** [comment]
@darkmatter18 I have same problem.

Basic example:

```
request('GET', `/auth?${code}`)
        .then(response => {
          if(signIn({
            token: response.token,
            tokenType: 'Bearer',
            authState: {id: 4},
            expiresIn: 10000000
          })){
            console.log(auth())
          } else{
            console.log('Error')
          }
        })
        .catch((error) => setError(error.reason))
```

`console.log(auth()` returns null even if I set `authState` directly with `id:4`.

Using version 2.7.1

**Comment by devakrishna33-fcfc** [comment]
@Kretiss This is the expected behaviour, behind the scenes react auth kit uses useReducer and it won't update the auth user immediately after calling sign in, it'll be done in next render. Correct me if I'm wrong @darkmatter18
