### ISSUE TITLE
Sign In tokenType different from 'Bearer' clears local storage

### ISSUE THREAD

**Issue by gabohc** [react-auth-kit/react-auth-kit#1164]
The Sign In documentation says that  ` tokenType: string | 'Bearer' `.  I only need the token itself because I'm adding something else to it. That's why I set `tokenType: ''`. It works and effectively gets the token (checked by printing it without refreshing) but it's not saved for other pages or refresh. 

How am I supposed to set it, if not 'Bearer'?

Somewhat similar issue: https://github.com/react-auth-kit/react-auth-kit/issues/876

 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version 2.7.1

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by monarcode** [comment]
i have similar problem, local storage clears after refresh..but i have Bearer set as auth type

**Comment by monarcode** [comment]
thanks a lot, just saw it now
