### ISSUE TITLE
How do i update the authState after editing some values in it so it gets the current values?

### ISSUE THREAD

**Issue by Moro-Afriyie** [react-auth-kit/react-auth-kit#1172]
**Prerequisites:**

Please answer the following questions for yourself before asking questions.

- [x] This is question only ❓
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not already asked
- [x] I'm asking the question in the correct repository

**Describe the question** \
Okay so all i'm trying to do is i have an api which edits the user details and sends the updated response back to me. so when i get the updated response, i want to set the new authState to the current response i got from the server but it seems there is no way to update it

**Related issues** \
If your question is containing an already created issue. Tag the issue

**Screenshots**
<img width="526" alt="Screenshot 2022-12-31 at 9 30 36 PM" src="https://user-images.githubusercontent.com/60523901/210155988-2830f8b7-c381-460d-bd4e-19a91f2bd124.png">

**Please provide the following information:**
 - OS: MacOs 13.0
 - Browser: Chrome
 - Version:  ^2.7.1
## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by devakrishna33** [comment]
You will have to call the signIn method again with updated values,

    const useUpdateReactAuthKitUserState = () => {
        const signIn = useSignIn();
        const authHeader = useAuthHeader();

        const [tokenType, token] = authHeader().split(" ");

        if (!tokenType || !token) {
            return () => {};
        }

        return (user) => {
            signIn({
                token,
                tokenType,
                expiresIn: ACCESS_TOKEN_EXPIRES_IN,
                authState: user,
            });
        };
    };

I have created this custom hook you can use to update the auth user.

**Comment by Moro-Afriyie** [comment]
thanks @devakrishna33 i guess this should be added to the documentation

**Comment by darkmatter18** [comment]
Hey @devakrishna33 and @Moro-Afriyie, thanks for the issue and the clarification as well. I think this can be a good small feature for Auth Kit.
I'll build it and will release it by the next release.

**Comment by Moro-Afriyie** [comment]
Yes sure. @darkmatter18

**Comment by santiagobaronz** [comment]
> You will have to call the signIn method again with updated values,
> 
> ```
> const useUpdateReactAuthKitUserState = () => {
>     const signIn = useSignIn();
>     const authHeader = useAuthHeader();
> 
>     const [tokenType, token] = authHeader().split(" ");
> 
>     if (!tokenType || !token) {
>         return () => {};
>     }
> 
>     return (user) => {
>         signIn({
>             token,
>             tokenType,
>             expiresIn: ACCESS_TOKEN_EXPIRES_IN,
>             authState: user,
>         });
>     };
> };
> ```
> 
> I have created this custom hook you can use to update the auth user.

Hi! Can you explain me how do you apply it?, i have been trying to use this solution but i couldn't :(
