### ISSUE TITLE
Refresh token - refreshApi with a type issue and console error

### ISSUE THREAD

**Issue by eliawk** [react-auth-kit/react-auth-kit#1185]
**Describe the bug** \
Using the refresh token in refreshApi.ts like indicated in the documentation and I get an error in the console.
Also TS is not happy about `refreshApiCallback` type:
```
Type '({ refreshToken }: { authToken?: string | undefined; authTokenExpireAt?: Date | undefined; refreshToken?: string | undefined; refreshTokenExpiresAt?: Date | undefined; authUserState: AuthStateUserObject | null; }) => void' is not assignable to type 'refreshTokenCallback'.
  Type 'void' is not assignable to type 'Promise<RefreshTokenCallbackResponse>'.ts(2322)
types.d.ts(95, 5): The expected type comes from property 'refreshApiCallback' which is declared here on type 'createRefreshParamInterface'
```

**To Reproduce** \
Implement the refresh api like this -> https://authkit.arkadip.dev/refreshtoken/#api-builder-example

**Screenshots**
![Schermata 2023-01-12 alle 12 36 02](https://user-images.githubusercontent.com/362016/212056834-80c2b397-f341-43ec-8f6e-2a450244853a.png)

**Desktop (please complete the following information):**
 - OS: mac OS 12.6 
 - Browser chrome
 - Version 108

**Failure Logs**
```
Uncaught TypeError: Cannot read properties of undefined (reading 'then')
    at Object.current (AuthProvider.tsx:55:16)
    at tick (hooks.ts:40:38)
```

**Comment by MrMoussie** [comment]
Same issue here.

**Comment by MrMoussie** [comment]
A fix for the `Cannot read properties of undefined (reading 'then')`:

Return the axios with your .post() and .then/ .catch() instance in the refreshApiCallBack function.

`refreshApiCallback: ({
    authToken,
    authTokenExpireAt,
    refreshToken,
    refreshTokenExpiresAt,
    authUserState,
  }) => {
    let promise = {
      isSuccess: false,
      newAuthToken: authToken,
      newAuthTokenExpireIn: authTokenExpireAt,
      newRefreshToken: refreshToken,
      newRefreshTokenExpiresIn: refreshTokenExpiresAt,
      newAuthUserState: authUserState,
    };

    return <your axios instance>.post("/token/refresh")...`
    
    PS. You still need to return the result in the .then and .catch clause:
    `return {
         isSuccess = true,
         ...
      }`

**Comment by ICS-Vortex** [comment]
> Fixing the documentation would already be sufficient to "fix" the issue, since there is only a return statement missing at the beginning of the arrow-function (before the axios.post...) To be more precise: Changing the documentation from
> 
> ```
> {refreshApiCallback: (
>     {   // arguments
>       authToken,
>       authTokenExpireAt,
>       refreshToken,
>       refreshTokenExpiresAt,
>       authUserState
>     }) => {
>     axios.post('/api/refresh',
>       {
>         refreshToken: refreshToken,
>         oldAuthToken: authToken
>       }
>     ).then(({data})=>{
>       return {
>         // As the request is successful, we are passing new tokens.
>         isSuccess: true,  // For successful network request isSuccess is true
>         newAuthToken: data.newAuthToken,
>         newAuthTokenExpireIn: data.newAuthTokenExpireIn
>         // You can also add new refresh token ad new user state
>       }
>     }).catch((e)=>{
>       console.error(e)
>       return{
>         // As the request is unsuccessful, we are just passing the isSuccess.
>         isSuccess:false // For unsuccessful network request isSuccess is false
>       }
>     })
>   }
> }
> ```
> 
> to
> 
> ```
> {refreshApiCallback: (
>     {   // arguments
>       authToken,
>       authTokenExpireAt,
>       refreshToken,
>       refreshTokenExpiresAt,
>       authUserState
>     }) => {
>     return axios.post('/api/refresh',
>       {
>         refreshToken: refreshToken,
>         oldAuthToken: authToken
>       }
>     ).then(({data})=>{
>       return {
>         // As the request is successful, we are passing new tokens.
>         isSuccess: true,  // For successful network request isSuccess is true
>         newAuthToken: data.newAuthToken,
>         newAuthTokenExpireIn: data.newAuthTokenExpireIn
>         // You can also add new refresh token ad new user state
>       }
>     }).catch((e)=>{
>       console.error(e)
>       return{
>         // As the request is unsuccessful, we are just passing the isSuccess.
>         isSuccess:false // For unsuccessful network request isSuccess is false
>       }
>     })
>   }
> }
> ```
> 
> would already fix this and close the issue.

![image](https://user-images.githubusercontent.com/13809571/229806135-fda86ff7-5c58-4cf1-9795-55b643e14e2c.png)

**Comment by RaninduJay** [comment]
add return doesn't work.
