### ISSUE TITLE
User undefined

### ISSUE THREAD

**Issue by azilRababe** [react-auth-kit/react-auth-kit#1187]
**useAuthUser()** returns undefined even though the `BrowserRouter` is wrapped in `AuthProvider`

**Comment by darkmatter18** [comment]
Can you please show that signin part?

**Comment by azilRababe** [comment]
> Can you please show that signin part?

 axios
      .post("auth/login", user)
      .then((res) => {
        signIn({
          token: res.data.accessToken,
          expiresIn: 60,
          tokenType: "Bearer",
          authState: {},
        });
        return navigate("/");
      })
      .catch((err) => console.log({ err: err }));

**Comment by vignxs** [comment]
any update on this ? I am also facing the same issue.

**Comment by azilRababe** [comment]
> any update on this ? I am also facing the same issue.

The `authState` shouldn't be an empty object 
instead it should be something like this `authState:{user: res.data.user}`
