### ISSUE TITLE
Warning: Cannot update a component while rendering a different component

### ISSUE THREAD

**Issue by MarcelGehring** [react-auth-kit/react-auth-kit#1193]
**Description**\
Warning message when accessing a secured page without beeing logged in.
```
react-dom.development.js:86 Warning: Cannot update a component (`AuthProvider`) while rendering a different component (`RequireAuth`). To locate the bad setState() call inside `RequireAuth`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at RequireAuth (http://localhost:3000/static/js/bundle.js:11361:21)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:39951:5)
    at Routes (http://localhost:3000/static/js/bundle.js:40394:5)
    at Router (http://localhost:3000/static/js/bundle.js:40332:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:38650:5)
    at RoutesComponent
    at AuthProvider (http://localhost:3000/static/js/bundle.js:11272:21)
    at App
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnAboutRenderPhaseUpdatesInDEV @ react-dom.development.js:27492
scheduleUpdateOnFiber @ react-dom.development.js:25498
dispatchReducerAction @ react-dom.development.js:17452
isAuth @ PrivateRoute.tsx:44
RequireAuth @ PrivateRoute.tsx:50
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSyncCallbacksOnlyInLegacyMode @ react-dom.development.js:12021
batchedUpdates$1 @ react-dom.development.js:26148
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
```

**How to reproduce(required)** \
Detailed steps to reproduce the behaviour you experienced 
1. Clone the react-auth-kit repo
2. Go to examples/create-react-app/src
3. yarn install && yarn start
4. in the browser navigate to localhost:3000/secure without logging in or login and logout
5. See the error in the console (i have exactly the same behaviour in my real app) 

**Correct behaviour** \
No Warning should be thrown under normal and expected operation

**Possible reason** \
Calling context.dispatch in PrivateRoute.tsx line 44 causes a state to be updated by the useReducer hook which leads to the warning.

**Screenshots**\
![image](https://user-images.githubusercontent.com/35878812/212691732-f4c02f7f-4489-4dc8-bc40-46f095a01785.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest
 - node 18.13

**Comment by JasmailDuck** [comment]
Receiving this same error too

**Comment by MrMoussie** [comment]
Same here!

**Comment by MrMoussie** [comment]
Potential fix thanks to @federicoguti01 and @davidbro-in

```js
const App = () => {
    //https://github.com/react-auth-kit/react-auth-kit/issues/1023
    const PrivateRoute = ({ Component }) => {
        const isAuthenticated = useIsAuthenticated();
        const auth = isAuthenticated();
        return auth ? <Component /> : <Navigate to="/login" />;
    };

    return (
        <AuthProvider authType={'cookie'}
            authName={'_auth'}
            cookieDomain={window.location.hostname}
            cookieSecure={window.location.protocol === "https:"}>
            <BrowserRouter>
                <div className="App">
                    <Navigation />
                    <Routes>
                        <Route path="/login" element={<Login />} />
                        <Route path="/home" element={<PrivateRoute Component={Home} />}></Route>
                    </Routes>
                </div>
            </BrowserRouter>
        </AuthProvider>
    )
}
export default App
```

**Comment by erdemkeren** [comment]
Still relevant.

**Comment by darkmatter18** [comment]
This issue is coming for the `signOut` operation. As the signout operation is responsible for a rerender and Navigate to login is taking place at the same time, the error is coming. 

Ref: https://github.com/react-auth-kit/react-auth-kit/blob/792dad79c4844d5f02dda2c92cf188cf3934c6c8/src/PrivateRoute.tsx#L58

**Comment by SaswatArabinda** [comment]
Here the issue is, the `signIn` method, takes time to update the context/cookie. In between if the user gets redirected to `ProtectedRoute`, it fails to authenticate` if (!isAuthenticated(context.authState)) {} `and forces the user to sign out.

```
    if (!isAuthenticated(context.authState)) {
        // Redirect them to the /login page, but save the current location they
        // were trying to go to when they were redirected. This allows us to
        // send them along to that page after they login, which is a nicer
        // user experience than dropping them off on the home page.
        context.dispatch(doSignOut());
        return React.createElement(Navigate, { to: loginPath, state: { from: location }, replace: true });
    }
```
We are completely blocked because of this. Is there any ETA for this bug?

**Comment by alessandrofoglia07** [comment]
Same error, when the token is refreshed with a refreshApi

**Comment by RafikiSmurfJr7** [comment]
I got the same error, anyone has an answer for this?

**Comment by kbanman** [comment]
The issue seems to be that during the redirect two components are being rendered (and having state changed) at the same time.
In my case I was able to work around this by deferring the redirect until the current component has finished a render:

```
if (loggedIn) {
    setTimeout(() => navigate(redirectTo ?? '/'));
    return <></>;
  }
```

**Comment by petermyers** [comment]
Looks like this has been open for a while, are there plans to address?

**Comment by fkbeys** [comment]
same problem :(

**Comment by Wamy-Dev** [comment]
same problem

**Comment by victor-ajayi** [comment]
Same problem here as well! :(

**Comment by victor-ajayi** [comment]
> The issue seems to be that during the redirect two components are being rendered (and having state changed) at the same time. In my case I was able to work around this by deferring the redirect until the current component has finished a render:
> 
> ```
> if (loggedIn) {
>     setTimeout(() => navigate(redirectTo ?? '/'));
>     return <></>;
>   }
> ```

what is `loggedIn`?

**Comment by WilliamDosSantos** [comment]
Adding a setTimeout for the route push resolution for me.

 if (!session) {
    setTimeout(() => {
      router.push("/login");
    }, 100);

    return null;
  }

**Comment by fkbeys** [comment]
const signout = useSignOut();

  const handleLogout = async () => {  
    navigate("/");
    setTimeout(() => {
      signout();
    }, 1000);
  };
  
  it worked for me...

**Comment by Xaypanya** [comment]
> ```js
>     const PrivateRoute = ({ Component }) => {
>         const isAuthenticated = useIsAuthenticated();
>         const auth = isAuthenticated();
>         return auth ? <Component /> : <Navigate to="/login" />;
>     };
> ```

Thanks

**Comment by Shadowrunner11** [comment]
For me what worked was setting a object to authState in signIn function param

**Comment by Yacobolo** [comment]
> For me what worked was setting a object to authState in signIn function param

This also worked for me!

**Comment by cestela** [comment]
> For me what worked was setting a object to authState in signIn function param

I tried this but still is throwing the warning

**Comment by vicsantizo** [comment]
My solution:
 
    function isTokenExpired(jwtAuthToken) {
        const encodedPart = jwtAuthToken.split(' ')[1]; // "Bearer eyJhbGciOiJ..."
        const decodedToken = jwt_decode(encodedPart); // using jwt_decode lib
     
        if (decodedToken.exp === undefined) return true;
        
        const expirationTimeMilliseconds = decodedToken.exp * 1000;
        const hasTokenExpired = Date.now() >= expirationTimeMilliseconds ? true : false;
        
        return hasTokenExpired;
    }

    const PrivateRoute = ({ YourProtectedComponent }) => {
        const isAuthenticated = useIsAuthenticated();
        const auth = isAuthenticated();

        const authHeader = useAuthHeader();
        const jwtAuthToken = authHeader();
        
        if (isTokenExpired(jwtAuthToken) && auth) {
            return YourProtectedComponent;
        }
        
        return <Navigate to="/login" />
    };

**Comment by vicsantizo** [comment]
```
const PrivateRoute = ({ YourProtectedComponent }) => {
    const isAuthenticated = useIsAuthenticated();
    const auth = isAuthenticated();

    const authHeader = useAuthHeader();
    const jwtAuthToken = authHeader();
    
    if (!isTokenExpired(jwtAuthToken) && auth) {
        return YourProtectedComponent;
    }
    
    return <Navigate to="/login" />
};

function isTokenExpired(jwtAuthToken) {
    if (!jwtAuthToken) return false; // does not exist
    const encodedPart = jwtAuthToken.split(' ')[1]; // "Bearer eyJhbGciOiJ..."
    const decodedToken = jwt_decode(encodedPart); // using jwt_decode lib
 
    if (decodedToken.exp === undefined) return true;
    
    const expirationTimeMilliseconds = decodedToken.exp * 1000;
    const hasTokenExpired = Date.now() >= expirationTimeMilliseconds ? true : false;
    
    return hasTokenExpired;
}
```

**Comment by jesusjoveruclm** [comment]
As @Shadowrunner11 says, skip authState in signIn throw this warning for me too (https://github.com/react-auth-kit/react-auth-kit/issues/1193#issuecomment-1627543050). Docs indicate that authState in signInConfig (https://authkit.arkadip.dev/signin/#signinconfig) is not optional, but table that explains signIn params indicate that it is (https://authkit.arkadip.dev/signin/#explanation-of-signinconfig). Seems table is wrong indicating this param is optional.

**Comment by amitsarkerr** [comment]
I got the same error.
I use useEffect https://nextjs.org/docs/pages/building-your-application/data-fetching/client-side

**Comment by darkmatter18** [comment]
React Auth Kit v3 solves this issue. To solve the issue please use any release after v3.
Thanks!
