### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by abolfazlakbarzadeh** [react-auth-kit/react-auth-kit#1199]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] This is bug in the application 🐛
- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository

**Describe the bug** \
A clear detailed description of what the bug is.

**To Reproduce** \
I put the 
```
<AuthProvider authType = {'cookie'}
                  authName={'_auth'}
                  cookieDomain={window.location.hostname}
                  cookieSecure={window.location.protocol === "https:"}>
 <Routes />
</AuthProvider>
```
and I got an error that said the "`Uncaught TypeError: Cannot read properties of null (reading 'useReducer')`" in the browser console

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 102

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

Note: my react.js version is 17.0.2

**Comment by darkmatter18** [comment]
Will reproduce locally!!
