### ISSUE TITLE
No signOut when the token could not be refreshed

### ISSUE THREAD

**Issue by ScriptSathi** [react-auth-kit/react-auth-kit#1223]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** \
A clear detailed description of what the bug is.

I have recently implement you library and i've noticed that when the token is refreshed, if the refresh has failed, it does not signOut the user.

**To Reproduce** \

Simply let the token expire and still trying to fetch data, even though it is expired

**Expected behavior** \

A normal behavior with make the user logged out and ask for his password again

**Current behavior** \
A clear and concise description of what is happening. If possible, give reasoning behind difference in current behavior and expected behavior

The user stayed sign In and the page continuously polling for data (even after refreshing the page)

**Possible solutions** (Optional) \
Give ideas for solving the problem, provide relevant links to additional packages you are mentioning

In AuthProvider.tsx, just add an else statement that signOut the user

``` # AuthProvider.tsx  - Line 58
if (result.isSuccess) {
  // store the new value using the state update
  dispatch(doRefresh(result));
} else {
  dispatch(doSignOut());
 }
```                
## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by darkmatter18** [comment]
Hey @ScriptSathi ,

The motivation for your Pull request is excellent, and I entirely agree with your concept.

But here is the thing, I don't want to directly signout the user, instead I am thinking to have a retry option. So the developer must provide the number of retries he wants before the user logout. If a network request fails for any reason, if will retry for n number of times, then declare it as a failed refresh, hence logout.

**Comment by darkmatter18** [comment]
I'll continue this issue to track the feature. If you find my solution well and suited comment below for your thoughts.

**Comment by ScriptSathi** [comment]
@darkmatter18 Any news for this feature ?

**Comment by returnvoid** [comment]
Hi, also wondering what's the proper way to check if the refresh token was not successfully refreshed and force signOut. In my case the refresh implementation works but not sure how to dispatch the action signOut. 
Thanks
