### ISSUE TITLE
NextJS support?

### ISSUE THREAD

**Issue by jelmd** [react-auth-kit/react-auth-kit#1238]
**Prerequisites:**

- [x] This is question only ❓
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not already asked
- [x] I'm asking the question in the correct repository

**Describe the question** \
I'm trying to get used/learn NextJS and wanna do that by creating a little app with user auths (and db backend is on the server). Just read the react and nextjs tutorials and did a
```
npm exec create-next-app ${APP_NAME}
npm install --save  react-auth-kit
```

Now I try to follow [Add Login/Auth to your React app in 5 mins](https://www.youtube.com/watch?v=wr3VmbZdVA4) as well as the [docs](https://authkit.arkadip.dev/integration/) but it doesn't seem to work, e.g.:
```
Cannot find module './routes' or its corresponding type declarations.ts(2307)
```

Do you have any hints how to fix it? Can you add some instructions or hints to the documentation? Or providing an example, which works out of the box would be great!

**Please provide the following information:**
 - OS: Linux (Ubuntu 20.04)
 - Browser: Firefox 111
 - Nodejs-Version: v18.15.0

**Comment by jelmd** [comment]
![vscode-screenshot](https://user-images.githubusercontent.com/4813414/226501770-12a88ef0-0037-445c-8d70-d5e5ac02a14e.gif)

**Comment by jelmd** [comment]
@LupuC thanx. IMHO the real problem is the chaotic shallow documentation of NextJS. If they would provide a "basic concepts" chapter, there would probably much less confusion. Right now it is like in old UNIX times: You need to know, what you are looking for (man $tool) ;-) .

Anyway, meanwhile after watching some youtube stuff and reading many docs I'm currently happy with:
```ts
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import React, { PropsWithChildren, useContext } from "react";
import GlobalCtx from "./global_ctx";

// components/session.tsx

/**
 * Ensure there is a session running when pages beneath /app/ are requested.
 * If not, just show a sign in message and stop the flow.
 * @param props page properties. Uses the auto generated `props.children` to
 * 	render the JSX componentens inside the `<EnsureSession>...</EnsureSession>`
 *  tag if a session exists and the user has loged in. Otherwise props.children
 *  get ignored.
 * @returns the page to render.
 */
const DEBUG = true;

export default function EnsureSession(props: PropsWithChildren) {
	const session = useSession();
	const router = useRouter();
	const ctx = useContext(GlobalCtx);

	if (session.status === 'loading') {
		if (DEBUG)
			return (
				<h1>Lade ...</h1>
			);
		return <></>
	}
	if (DEBUG) console.log('EnsureSession:\n', session);
	if ((session !== null && session.status === 'authenticated')
		|| (!router.pathname.startsWith('/app/') && router.pathname !== '/app'))
	{
		// We rely on userUpdate() that it does the right thing.
		ctx.userUpdate(session.data?.user);

		return (
			<>
				{props.children}
			</>
		);
	}

	router.push('/api/auth/signin');
	return <></>;
}
```
and
```ts
import '@/styles/reset.css';
import '@/styles/globals.css';
import '@/styles/misc.css';
import '@/styles/dashboard.css';

import type { AppProps } from 'next/app';
import { SessionProvider } from "next-auth/react";
import { StrictMode } from 'react';
import EnsureSession from '@/components/session';
import { GlobalCtxProvider } from '@/components/global_ctx';
import { SESSION_TIMEOUT } from '@/lib/utils';
import Layout from '@/components/layout';

// pages/_app.tsx

export default function App ({ Component, pageProps: { session, ...pageProps } }:
	AppProps) 
{
	let s = process.env.APP_CONTEXT ?? '';
	s = s.trim();
	const APP_CONTEXT = s.startsWith('/') ? s.substring(1) : s;

	return (
		<StrictMode>
		<GlobalCtxProvider> {/* needs to sit here to survive session updates */}
			<SessionProvider session={session}
				refetchInterval={SESSION_TIMEOUT} basePath={APP_CONTEXT}>
				<EnsureSession>
					<Layout>
						<Component {...pageProps} />
					</Layout>
				</EnsureSession>
			</SessionProvider>
		</GlobalCtxProvider>
		</StrictMode>
	);
}
```

**Comment by jelmd** [comment]
The solution seems to be: do not use routes.

**Comment by darkmatter18** [comment]
I will create the next plugin by the end of January. OSS's contribution will be appreciated.

**Comment by ImSingee** [comment]
@darkmatter18 Hope to see Next.js support! By the way, the `createStore` with localstorage cannot be used in the SSR environment (it tries to access the `localstorage` but it does not exist in server environment)

**Comment by darkmatter18** [comment]
Next JS support is added on V3.1.0, but for now it's only uses Client Side Rendering. Hope to see SSR in near future.
