### ISSUE TITLE
signOut() problem 

### ISSUE THREAD

**Issue by aufgussmeister** [react-auth-kit/react-auth-kit#1243]
Hi, I get this error:

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops
Please answer the following questions for yourself before submitting an issue.

Maybe I'm wrong in some passages. Login and redirect to home works good. when I click on logOut I get the problem 

Thanks

### Home

```js
import React from 'react'
import {useAuthUser} from 'react-auth-kit'
import { useSignOut } from 'react-auth-kit'

const Home = () => {
    const auth = useAuthUser()
    const signOut = useSignOut()
    return(
        <div>
            Hello {auth().username}
            <button onClick={() => signOut()}>Sign Out</button>
        </div>
    )
}

export default Home;
```

### Login 

```js
import React from "react"
import axios from 'axios'
import { useSignIn } from 'react-auth-kit'
import { useNavigate } from 'react-router-dom';

const Login = () => {
    const signIn = useSignIn()
    const [formData, setFormData] = React.useState({username: '', password: ''})
    const navigate = useNavigate();

    const onSubmit = (e) => {
        e.preventDefault()
        
        axios.request({
            url: "/oauth/token",
            method: "post",
            baseURL: "http://localhost:8080",
            
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Authorization': 'Basic ' + btoa('client:secret'),
            },
            
            data: {
              "grant_type": "password",
              "username":formData.username,
              "password":formData.password,   
            }
          })
            .then((res)=>{
                if(res.status === 200){
                    if(signIn(
                        {
                            token: res.data.access_token,
                            expiresIn:res.data.expires_in,
                            tokenType: "Bearer",
                            authState: {username: formData.username},
                            refreshToken: 31536000,                    // Only if you are using refreshToken feature
                        }
                    )){ 
                       navigate('/home');
                    }else {
                       alert("errore autenticazione") 
                    }
                }
            }).catch((res)=>{
                alert(res.response.data.error_description)
            })
    }

    return (
        <form onSubmit={onSubmit}>
            <input type={"username"} onChange={(e)=>setFormData({...formData, username: e.target.value})}/>
            <input type={"password"} onChange={(e)=>setFormData({...formData, password: e.target.value})}/>

            <button>Submit</button>
        </form>
    )
}

export default Login;
```

### App

```js
import './App.css';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider, RequireAuth } from 'react-auth-kit'
import Login from './components/login';
import Home from './components/home';

function App() {
  return (
    <AuthProvider authType = {'cookie'}
                  authName={'_auth'}
                  cookieDomain={window.location.hostname}
                  cookieSecure={window.location.protocol === "https:"}>
      <BrowserRouter>
            <Routes>
              <Route path="/login" element={<Login />} />
                <Route
                    path="/redirect"
                    element={ <Navigate to="/login" /> }
                />
              <Route path={'/home'} element={
                  <RequireAuth loginPath={'/login'}>
                    <Home/>
                  </RequireAuth>
                }/>
            </Routes>
      </BrowserRouter>
    </AuthProvider>
   
  );
}
```

**Comment by darkmatter18** [comment]
@aufgussmeister Please share the `package.json`, so that I can reproduce it locally.

**Comment by aufgussmeister** [comment]
{
  "name": "oauth_kit",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    ***@***.***/jest-dom": "^5.16.5",
    ***@***.***/react": "^13.4.0",
    ***@***.***/user-event": "^13.5.0",
    "axios": "^1.3.4",
    "react": "^18.2.0",
    "react-auth-kit": "^2.8.3",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "react-router": "^6.9.0",
    "react-router-dom": "^6.9.0"
  }
}

**Comment by hookenful** [comment]
Any updates on this? Have the same problem

**Comment by hookenful** [comment]
@darkmatter18 @aufgussmeister I've figured that downgrading to React 17 fixed the problem

**Comment by KimberlyYang** [comment]
downgrading to   
  "react": "^18.1.0",
  "react-dom": "^18.1.0",
  worked for me

**Comment by briancoates** [comment]
also having this issue.  downgrading to react 18.1 didn't solve for me

**Comment by MarioKrstevski** [comment]
I also have this issue, I'm using  "react": "^18.2.0", downgrading is not an option for me, so can someone take a look into this ^^

**Comment by Mattc1221** [comment]
I'm having the same issue, downgrading to react 18.1 did not work for me either 😢

**Comment by digvijayJUIT** [comment]
> I'm having the same issue, downgrading to react 18.1 did not work for me either 😢
> 
> The workaround I used was to navigate to the login page before calling `signOut`. Ex.
> 
> ```js
> onClick={() => {
>     nav("/login");
>     signOut();
> }}
> ```

wow Its resolve the issue. thanks @Mattc1221 .

**Comment by darkmatter18** [comment]
Solved in React Auth Kit v3. Please use the same.

Thanks!!
