### ISSUE TITLE
Issues with Tokens Expiration dates and weird cookie behavior

### ISSUE THREAD

**Issue by ICS-Vortex** [react-auth-kit/react-auth-kit#1261]
Hello. I am trying to implement JWT Authentication into my React (+TS) application. 
Along with docs - I wrote next code: 
index.tsx
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import 'flag-icons/css/flag-icons.css'
import App from './App';
import {DevSupport} from "@react-buddy/ide-toolbox";
import {ComponentPreviews, useInitial} from "./dev";
import {setupStore} from "./store";
import {Provider} from 'react-redux';
import './i18n';
import refreshApi from "./api/refreshApi";
import {AuthProvider} from "react-auth-kit";

const root = ReactDOM.createRoot(
    document.getElementById('app') as HTMLElement
);

const store = setupStore();

root.render(
    <AuthProvider authType={'cookie'}
                  authName={'_auth'}
                  cookieDomain={window.location.hostname}
                  cookieSecure={process.env.NODE_ENV === 'production'}
                  refresh={refreshApi}
    >
        <DevSupport ComponentPreviews={ComponentPreviews} useInitialHook={useInitial}>
            <Provider store={store}>
                <App/>
            </Provider>
        </DevSupport>
    </AuthProvider>
);
```
My App.tsx contains a few routes.
```
import React from 'react';
import './App.css';
import {BrowserRouter, Route, Routes} from "react-router-dom";
import Layout from "./components/layout/Layout";
import {HomePage} from "./pages/home/HomePage";
import LoginPage from "./pages/login/LoginPage";
import RequiresAuth from "./components/routes/RequiresAuth";
import TestPage from "./pages/home/TestPage";
import {PAGE_HOME, PAGE_LOGIN, PAGE_REGISTRATION} from "./routes";
import RegistrationPage from "./pages/registration/RegistrationPage";

function App() {
    return (
        <BrowserRouter>
            <Routes>
                <Route path="/" element={<Layout/>}>
                    <Route path={PAGE_HOME} element={<HomePage/>}/>
                    <Route path={PAGE_LOGIN} element={<LoginPage/>}/>
                    <Route path={PAGE_REGISTRATION} element={<RegistrationPage/>}/>
                    <Route element={<RequiresAuth/>}>
                        <Route path="/test" element={<TestPage/>}/>
                    </Route>
                </Route>
            </Routes>
        </BrowserRouter>
    );
}

export default App;

```

I have API backend running on Symfony 6.2 (PHP8.1-fpm)  with Lexik JWT Bundle + Gesdinet Refresh Token Bundle. 
Backend has a few routes:
`api/login`
`api/token/refresh`
and some private routes.

The problem is next: I try to login first: 
```
const onFormSubmit = async () => {
        try {
            setDisabled(true)
            const response = await axios.post<ILoginResponse>(API_LOGIN, {
                username: emailRef?.current?.value, password: passwordRef?.current?.value
            });
            const config = {
                token: response.data.token,
                expiresIn: 10 + getTimeZoneOffset(),
                tokenType: 'Bearer',
                refreshToken: response.data.refreshToken,
                refreshTokenExpireIn: 600 + getTimeZoneOffset(),
            };
            if (signIn(config)) {
                navigate(PAGE_TEST);
            }
        } catch (e) {
            console.error(e);
        } finally {
            setDisabled(false)
        }
    }

export const getTimeZoneOffset = () : number  =>  {
    const date = new Date();
    const offset = date.getTimezoneOffset();
    if (offset === 0) {
        return 1;
    }
    return Math.abs(offset);
}
```

Login works fine. But when I check cookies - I see weird Expiration dates for _auth_token and _auth_refresh cookies.

- From what I see, expiration date is calculated starting from time that is taken as UTC 0. But basically, I live in UTC +3 (Ukraine/Kiev) timezone. 

I tried to calculate an offset in minutes - because token `expiresIn` prop  - as per docs - is of type number.
So, my token TTL is 10 minutes + 180 minutes - works fine. But refreshTokenExpireIn date is the same as expiresIn. 
So, basically, expiration dates for access and refresh tokens are the same. I am looking in Chrome Dev Tools => Application => Cookies => Localhost...

![image](https://user-images.githubusercontent.com/13809571/229883343-50e05447-f70e-44b4-826e-a1f23770a365.png)

I logged in at 21:21. So, seems to me, access token expiration is applied to refresh expiration. They are equal. But should differ on 590 minutes. 

And I found another issue. When I refresh page - all cookies with prefix set in AuthProvider - _auth in my case - are deleted. 
Chrome Dev Tools => Application => Cookies => localhost - just are empty. 
Is this a normal behavior of the react-auth-kit ? From what I understand, lib shouldn't act like this. 

General information:
 - OS: Windows 11
 - Browser : Google Chrome
 - Version: 111.0.5563.147

package.json libraries:
```
{
  "name": "vpc-frontend",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@react-buddy/ide-toolbox": "^2.3.1",
    "@reduxjs/toolkit": "^1.9.3",
    "axios": "^1.3.4",
    "flag-icons": "^6.6.6",
    "i18next": "^22.4.14",
    "i18next-http-backend": "^2.2.0",
    "localforage": "^1.10.0",
    "react-auth-kit": "^2.10.0",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0",
    "react-i18next": "^12.2.0",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.10.0",
    "react-slideshow-image": "^4.2.1",
    "shortid": "^2.2.16",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.23",
    "@types/react": "^18.0.31",
    "@types/react-dom": "^18.0.11",
    "react-scripts": "^5.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by Krelsis** [comment]
> I found another issue. When I refresh page - all cookies with prefix set in AuthProvider - _auth in my case - are deleted.

I also observe this behaviour, on version 1.x. Seems that it even happens where `"Authentication"` instead of `"_auth"`.

Likely to be an issue in [AuthProvider.tsx](https://github.com/react-auth-kit/react-auth-kit/blob/f12a44bd86e22fed4e5c26e2d17f2bcbe37544d4/src/AuthProvider.tsx#L68) where syncTokens might be getting invoked with the initialToken or undefined on page load.

Can be replicated via : 

1. Login.
2. Duplicate page in a new tab
3. Navigate to a different route.
4. Close the tab
5. Open new tab, manually re-visit site, observe logged out state. (All Cookies deleted)
6. Re-visit original tab, refresh tab, observe logged out state. (All Cookies deleted).

I too am likely to uninstall auth kit and use a bespoke solution as if this issue does get fixed, it is unlikely to be retroactively updated in v1.x, which is a shame as I am currently dependant on it as I currently use ReactRouter@5.

**Comment by alessandrofoglia07** [comment]
same problem
