### ISSUE TITLE
Reloading the page does not persist logged-in users

### ISSUE THREAD

**Issue by ZiedChekir** [react-auth-kit/react-auth-kit#1299]
**Prerequisites:**

Please answer the following questions for yourself before asking questions.

- [ +] This is question only ❓
- [ +] I am running the latest version
- [ +] I checked the documentation and found no answer
- [ +] I checked to make sure that this is not already asked
- [ +] I'm asking the question in the correct repository

**Describe the question** \
Everything works correctly however when I reload the page it doesnt matter if I am logged-in, I will be redirected to the Login page. Is there a way to prevent this ? even if the page reloads is there way to keep the user logged in ? 
At first, I thought this is handled by the refresh token but after reading the implementation I dont think it is meant for this purpose. please correct me if I am wrong

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by samgreentips** [comment]
> Just set `authState` in`signIn` params and you will be gucci. You can set it with empty object if nothing to store

this doesn't work in production, almost as if the cookies do not 'set' when in prod environment, been banging my head for days as to why

**Comment by hookenful** [comment]
> > Just set `authState` in`signIn` params and you will be gucci. You can set it with empty object if nothing to store
> 
> this doesn't work in production, almost as if the cookies do not 'set' when in prod environment, been banging my head for days as to why

Does this problem persists when you store data in local storage?

**Comment by specialobyno** [comment]
I am having the same issue. Every auth data in the browser cookies wipes off on reload. How to persist the user even on reload?

**Comment by ithomaslin** [comment]
I'm having the same issue, by reloading the page, all data is wiped out.

**Comment by vmoosCode** [comment]
hello, i set authState in signin params and it works as expected,

**Comment by maxcmoi89** [comment]
I am using localstorage and Hookenful's solution fixed it for me : `authState: {}`

**Comment by tecnomage** [comment]
i was with the same problem,  i set authState in signin params and it works fine.

**Comment by JigarSoni5** [comment]
I'm having a same problem

**Comment by t0mdd** [comment]
I am getting this problem too. I am using AuthProvider to set a cookie and I am passing an authState object to the signIn function but the cookie gets deleted on refreshing the page or opening another page in a new tab.

**Comment by Andi-gech** [comment]
> > Just set `authState` in`signIn` params and you will be gucci. You can set it with empty object if nothing to store
> 
> this doesn't work in production, almost as if the cookies do not 'set' when in prod environment, been banging my head for days as to why

>>How to fix it in production

**Comment by Andi-gech** [comment]
Setting auth state not work in production

**Comment by darkmatter18** [comment]
Please use V3, if you are still facing the issue, let me know.

**Comment by codeomi** [comment]
> > > Just set `authState` in`signIn` params and you will be gucci. You can set it with empty object if nothing to store
> > 
> > 
> > this doesn't work in production, almost as if the cookies do not 'set' when in prod environment, been banging my head for days as to why
> 
> Does this problem persists when you store data in local storage?

In localStorage it does not matter if you reload as it will not affect the values in localStorage.
Eg: If you are logged in and you set in your localStorage, even if you reload it wont change its value and you will stay logged.

**Comment by codeomi** [comment]
I guess you are using slice or any other global variable to store your log in info , due to which whenever you reload state gets reloaded as well and you will are loosing your log in info.

**Solution ->** What you can do is....Once the user is logged in create a JWT token of it and store it in localStorage which will not be lost after reloading and you will have all the user info.

**Good to have ->** Additionally you can also encrypt the JWT token before storing it to increase the security level of user info. Use a custom hook to decrypt it whenever necessary.

**Comment by bhupeshg** [comment]
Did we find any solution to this yet?
