### ISSUE TITLE
Error show Cannot use import statement outside a module in Next.js

### ISSUE THREAD

**Issue by parth25** [react-auth-kit/react-auth-kit#1372]
when i implement in next js getting below error 

`import AuthProvider from './AuthProvider.js';

SyntaxError: Cannot use import statement outside a module

here is _app.js code 

import Aos from "aos";
import SrollTop from "../components/common/ScrollTop";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "swiper/css/scrollbar";
import "swiper/css/effect-cards";
import "aos/dist/aos.css";
import "../styles/index.scss";
import {store} from "../app/store";
import {Provider} from "react-redux";
import {useEffect} from "react";
import { AuthProvider } from 'react-auth-kit';

if (typeof window !== "undefined") {
    require("bootstrap/dist/js/bootstrap");
}

export default function App({Component, pageProps: {...pageProps}}) {

    useEffect(() => {
        Aos.init({
            duration: 1200,
            once: true,
        });
    }, []);

    return (
        <AuthProvider authType="localstorage" authName="_auth">
            <main>
                <Provider store={store}>
                    <Component {...pageProps} />
                    <SrollTop/>
                </Provider>
            </main>
        </AuthProvider>
    );
}`

**Comment by ForeshadowRU** [comment]
same error here

**Comment by darkmatter18** [comment]
Same as #1385
