### ISSUE TITLE
[documentation request] testing with react-auth-kit

### ISSUE THREAD

**Issue by FranciscoKloganB** [react-auth-kit/react-auth-kit#1382]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is a related to documentation only 📃
- [ ] I am running the latest version
- [x] I checked the documentation regarding this
- [x] I checked to make sure that this request has NOT already been made

## Description

As a future-user, I would like to have a small page dedicated to perform tests (unit, integration) on components using this library.

It is quite common for projects with authentication and authorization requirements to implement the following:

- Mocked `AuthProvider`
- Mocked `useAuthUser` and similar hooks
- Apply spy's on `useAuthUser` and similar hooks without changing their implementations

Etc.

While I can probably figure this out by myself, it would be nice to have simple and/or get started examples in order to reduce cognitive fadigue when adding this lib to codebases.

**Comment by darkmatter18** [comment]
Hey,

Can you please suggest some document from any other library?

**Comment by FranciscoKloganB** [comment]
Hey @darkmatter18 sorry for the delay;

Here are some examples I found of libraries giving examples on how to test using them:

- https://pinia.vuejs.org/cookbook/testing.html (vue pinia store)
- https://next-auth.js.org/guides/testing (next-auth, for cypress)
