### ISSUE TITLE
[docs] False statement about Next.js support

### ISSUE THREAD

**Issue by ForeshadowRU** [react-auth-kit/react-auth-kit#1385]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is a related to documentation only 📃
- [x] I am running the latest version
- [x] I checked the documentation regarding this
- [x] I checked to make sure that this request has NOT already been made

**Description**\
As of now, this line in documentation should be removed:
![image](https://github.com/react-auth-kit/react-auth-kit/assets/24393965/ff7b432a-453f-4db7-a2a1-e18135ca5b13)

It's just false statement. Library not only incompatible with latest Next 13.4, but any other as well.

There are some window. calls in
```
AuthProvider.defaultProps = {
  cookieDomain: window.location.hostname,
  cookieSecure: window.location.protocol === 'https:',
};
```
After fixing that in local copy, there are next challange: 
![image](https://github.com/react-auth-kit/react-auth-kit/assets/24393965/3b5d6091-ecec-49cf-a44f-0bcba973a954)

That doesn't seems like next.js support (using Next.js 13 with plain old pages directory, no App Router).

Also [rollup as for now](https://github.com/rollup/rollup/issues/4699) does not support 'use client' directives which means no support for Next.js 13 App Router in nearest future.

Though this could be a great library for specific needs like admin areas or so (for anything bigger there is NextAuth).

My Suggestion either to provide a full Next.js support, or remove this line from documentation, because for now it produces many question in project issues.

**Comment by darkmatter18** [comment]
@ForeshadowRU You are right. I had never gotten the time to test the next JS comfortability. My thought process was straightforward, both are based on React JS, so there shouldn't be any problem. I'll see, what next step I can take. Thanks!

**Comment by darkmatter18** [comment]
@ForeshadowRU You are right. I had never gotten the time to test the next JS comfortability. My thought process was straightforward, both are based on React JS, so there shouldn't be any problem. I'll see, what next step I can take. Thanks!

**Comment by Kavan72** [comment]
@darkmatter18 any update ? and does this lib support next.js in future ?
