### ISSUE TITLE
authkit.arkadip.co is down

### ISSUE THREAD

**Issue by shackra** [react-auth-kit/react-auth-kit#144]
**Describe the bug**
the site where the documentation is host is no longer available

**To Reproduce**
1. Go to https://authkit.arkadip.co/
2. the site won't load.

**Expected behavior**
The site loads and you can read the documentation.

**Comment by darkmatter18** [comment]
@shackra Thank you for your feedback. It's my fault. I changed the name, but forget to change it.

The new name is https://authkit.arkadip.me/

Sorry for your inconvenience.
