### ISSUE TITLE
Does anyone implement role based routing ?

### ISSUE THREAD

**Issue by hassan6846** [react-auth-kit/react-auth-kit#1508]
**Prerequisites:**

Please answer the following questions for yourself before asking questions.

- [x] This is question only ❓
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not already asked
- [x] I'm asking the question in the correct repository

**Describe the question** \
A clear detailed description of what is your question.
Give correct refrences asked in question

**Related issues** \
If your question is containing an already created issue. Tag the issue

**Screenshots**

**Please provide the following information:**

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by arsrivastawa** [comment]
Hey, This is Aditya, a Full stack MERN Developer and I have good grasp on User Authentication & RBAC (Role-Based-Access-Control).

**Comment by darkmatter18** [comment]
@arsrivastawa If you can help me that'll be awesome. Let me what features should wee have in the library to make it Role based routing

**Comment by arsrivastawa** [comment]
@darkmatter18 there are many node packages like express, jasonwebtoken, axios etc. which are gonna help us in order to achieve this. You can mail me at arsrivastawa2710@gmail.com . So, that we continue further
