### ISSUE TITLE
Async useSignIn/useIsAuthenticated

### ISSUE THREAD

**Issue by allan-vera** [react-auth-kit/react-auth-kit#1512]
So I am using this package for my authentication. My user signs in successfully and is redirected to a page where that page before each load checks to see if user is authenticated via `useIsAuthenticated()();` -> if it is it continues as normal, if not redirects them to login. 

However, it seems like useIsAuthenticated()(); is not updated as soon as signIn() is called. As by the time my page checks to see if the user is authenticated, the hook still returns false. Is there a way I can force my application to wait until signIn has updated everything correctly?

I dont see anything in docs that suggests that signin is async so a bit stuck.

**Comment by darkmatter18** [comment]
Which version are you using?
