### ISSUE TITLE
how to use useAuthUser? 

### ISSUE THREAD

**Issue by alex931d** [react-auth-kit/react-auth-kit#1551]
**Prerequisites:**

Please answer the following questions for yourself before asking questions.

- [x] This is question only ❓
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not already asked
- [x] I'm asking the question in the correct repository

**Describe the question** \
i tried to set up react auth kit for my project but couldn't get useAuthUser() to work
my problem is i can't set data for the authUser here is my signIn function:
```
    signIn({
          token: response.data.token,
          expiresIn: 3600,
          tokenType: "cookie",
          authState: {
            isAuthenticated: true,
          },
          userState:{
            userdata: response.data.user,
            devLinks: response.data.devlink,
          }

        });
```
as the documentation shows an userState is used to so i tried doing the same but with no result when i tries to console.log useAuthUser its empty 
```

export function APIContextProvider({ children }) {
  const [loading, setLoading] = useState(true);
  const authUser = useAuthUser()
  const isAuthenticated = useIsAuthenticated()
  useEffect(() => {
  const fetchData = async () => {
    if (isAuthenticated) {
      console.log(authUser) // returns empty 
    try {
      const [userInfoResponse, devLinksResponse] = await Promise.all([
        axios.post('/api/getuserinfo'),
        axios.post('/api/getdevlinks'),
      ]);

      const userInfo = userInfoResponse.data.userInfo;
      const devLinks = devLinksResponse.data.allDevLinks[0];

      if (devLinks && userInfo) {
        serverData = {
          _id: devLinks._id || '',
          links: devLinks.links || [],
          medias: devLinks.medias || [],
          notes: devLinks.notes || [],
          userInfo: {
            firstName: userInfo.name || '',
            lastName: userInfo.last_name || '',
            email: userInfo.email || '',
            profileImg: userInfo.profile_picture || '',
            profileBlob: '', // used for the blob temp
          },
          profileInfo: {
            ...initialState.profileInfo,
            ...devLinks,
          },
        };
       dataLoaded = true;
      } else {
      }
    } catch (error) {
      setLoading(false);
    } finally {
      setLoading(false);
    }
  };
}
  fetchData();
}, [isAuthenticated]);
```

## Version
im running version 3.0.2-alpha.8 

## License

[MIT](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by darkmatter18** [comment]
Try to make

```js
const fetchData = async () => {
    if (isAuthenticated) {
...
```

To

```

const fetchData = async () => {
    if (isAuthenticated()) { // added brackets here
...
```

**Comment by alex931d** [comment]
> Try to make
> 
> ```js
> const fetchData = async () => {
>     if (isAuthenticated) {
> ...
> ```
> 
> To
> 
> ```js
> const fetchData = async () => {
>     if (isAuthenticated()) { // added brackets here
> ...
> ```

did but useAuthUser still returns empty 
here is what it returns
```
function useAuthUser()
length: 0
name: ""
prototype: Object { … }
<prototype>: function ()
```

**Comment by darkmatter18** [comment]
Hey Alex, let's have an in-person call. https://calendly.com/arkadip/react-auth-kit

**Comment by alex931d** [comment]
> Hey Alex, let's have an in-person call. https://calendly.com/arkadip/react-auth-kit

hello no need i think the documentation on https://authkit.arkadip.dev/getting_started/authdata/ is poorly written , i discovered a solution for my niche problem by adding `()` to the end of `authUser` i was able to access my authState data still i have no idea how to access my  userState that i set in my signIn but i solutioned my problem by adding the fields to my authState
