### ISSUE TITLE
Cookie Expiration time in the latest version(3.0.2-alpha.19)

### ISSUE THREAD

**Issue by feyiamujo1** [react-auth-kit/react-auth-kit#1566]
Hi, I was trying to follow the documentation for the latest version but I couldnt find how to add cookie expiration time.

Code is below - 
signIn({
            auth: {
              token: response?.data?.detail?.token,
              type: 'Bearer',
            },
            userState: {
              username: response.fName,
              role: response.role,
            }
          })

**Comment by darkmatter18** [comment]
The expiration time will be fetched from the `exp` payload of the JWT token. For access token expiration time, the access token's `exp` param will be used and for refresh token expiration time, the refresh token's `exp` payload will be used. 

https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4
