### ISSUE TITLE
Unstable behaviour after upgrade to version 3

### ISSUE THREAD

**Issue by goodgiftdesign** [react-auth-kit/react-auth-kit#1582]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] This issue is related to a behaviour of the application only
- [ ] I am running the latest version
- [ ] I checked the documentation regarding this issue and found no solution
- [ ] I checked to make sure that this issue has NOT already been filed
- [ ] I'm reporting the issue to the correct repository

**Description**\
Elaborate the unexpected behaviour you encountered...

**How to reproduce(required)** \
Detailed steps to reproduce the behaviour you experienced 

**Correct behaviour** \
Description of the correct behaviour you expected...

**Possible reason**(Optional) \
If possible give the reasoning for experiencing this unexpected behaviour

**Screenshots**\

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

## License

[MIT](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by darkmatter18** [comment]
What's your expected and desired behavior? Please elaborate. Thanks
