### ISSUE TITLE
Means for refreshing your tokens

### ISSUE THREAD

**Issue by shackra** [react-auth-kit/react-auth-kit#162]
It seems the library have no means for you to refresh the user's tokens. My backend returns a refresh token along with an access token.

**Describe the solution you'd like**
means for receiving the tokens you have stored to do the token refreshing.

**Comment by darkmatter18** [comment]
@shackra Can you please tell me, how you are refreshing the token so that I can understand it deeply.

**Comment by shackra** [comment]
> @shackra Can you please tell me, how you are refreshing the token so that I can understand it deeply.

sure.

What I do on my project is loading the refresh token (is a token like the access token but with some values changed that are checked on my backend to ensure it is different from the access token) in the `Authorization` header of a GET request to my endpoint, the backend returns the same type as that when the user provides his credentials to login.

People may do this different, tho.

**Comment by shackra** [comment]
on the other hand, in the same component where I check if the user is logged or not, I should do the checking there and do the refreshing there, thus I just use your `signIn` as normal. My issue with this approach is that react-auth-kit provides means for storing your access token only, thus if I want to keep the refresh token around I need to build my own solution for that.

**Comment by shackra** [comment]
hey @darkmatter18 thanks for your hard work!

in your example on your documentation I read the following snippet of code:

```
    const {authToken, authTokenType, expireAt} = refreshToken.getCurrentAuthState() //Get the current state
```

the `authToken` and `expireAt`, where do they come? are they the same as those you pass to `useSignIn()`?

I was wondering this since `useSignIn` stills receives one (1) token instead of, say, two (1 for access and 1 for refreshing). Thoughts?

**Comment by darkmatter18** [comment]
Hey @shackra 

I noticed that actually did not complete the issue, as the concept of the refresh token is missing there. But I completed the stuff. 

I am requesting you to check the pre-patch version `v1.4.1-0`

I already tested the codebase. But as the testing is not completed yet, I thought it would be better to leave it on the pre-version.

I am also requesting, that if you can test the code. if it is working properly or not.
If it is working properly, then let me know here, otherwise please float an issue for that.

Thanks!

**Comment by shackra** [comment]
@darkmatter18 please re-open this issue

I found out that the expirations of the access and refresh tokens are waaaaaaaay beyond the future:

```
{
  "expireAt": "5079-08-22T00:11:03.626Z",
  "refreshTokenExpireAt": "5079-09-08T12:11:03.626Z"
}
```

my backend [already returns the expiration time as a Unix timestamp](https://pkg.go.dev/github.com/gbrlsnchs/jwt/v3#Time):

```
{
  "expiresIn": 1608700332,
  "refreshTokenExpireIn": 1608725532
}
```

But, passing the values as-is may be my fault tho.

I also discovered that the data of the refresh token disappears after a refresh:

```
{
  "expireAt": "5079-08-22T00:11:03.626Z",
  "refreshTokenExpireAt": null
}
```

that's a bug.

**Comment by darkmatter18** [comment]
Hey @shackra 

Please test the `v1.4.3-0`. Hope this has fixed all the errors

**Comment by shackra** [comment]
Issue fix! After login and refreshing manually the page the refresh token is kept in the browser!

```
{
  "tokenExpired": false,
  "refreshTokenExpired": false,
  "expireAt": "2020-12-23T18:34:33.000Z",
  "refreshTokenExpireAt": "2020-12-24T01:34:33.000Z"
}
```

But please review the documentation, I believe the full examples aren't that "real world" accurate.

**Comment by shackra** [comment]
but you can ship this as it is currently is, IMHO

**Comment by darkmatter18** [comment]
Good to hear that it's working!

Can you help me to polish the documentations? It will be so helpful to me

**Comment by shackra** [comment]
Sure thing, I can take a look to my own code and polish your documentation
accordingly.

**Comment by darkmatter18** [comment]
Hey @shackra 

It becomes so long. Do you have any updates?

**Comment by shackra** [comment]
> Hey @shackra 
> 
> It becomes so long. Do you have any updates?

no, I'm sorry, but Christmas and New Year came and pass

**Comment by shackra** [comment]
I could work something tonight (in 9 hours)

**Comment by darkmatter18** [comment]
Please follow the issue #191
