### ISSUE TITLE
problem with useIsAuthenticated hook

### ISSUE THREAD

**Issue by saji-nael-98** [react-auth-kit/react-auth-kit#1660]
I am using useIsAuthenticated, but it is not working until I reload the app.

I believe there may be an issue with the state of the context.

**Comment by MKSisti** [comment]
same issue here, I'm trying to implement protected routes with Tanstack/router instead of react-router, and the hook doesn't update when auth changes which makes the context inside the router always 'false' until app is reloaded then it resolves to 'true'

**Comment by darkmatter18** [comment]
Same as #1541
