### ISSUE TITLE
Bug - refresh token not working

### ISSUE THREAD

**Issue by kailashkaji** [react-auth-kit/react-auth-kit#1714]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] This is bug in the application 🐛
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

**Describe the bug** \
A clear detailed description of what the bug is.
if the refresh token is setup in the system whole auth kit stop working.
here is my code snippet 
![image](https://github.com/react-auth-kit/react-auth-kit/assets/134660342/c1669dd1-dccb-4301-b993-a4e7772754be)

import axios from "axios";
import createRefresh from "react-auth-kit/createRefresh";

const refresh = createRefresh({
  interval: 0.1,
  refreshApiCallback: async (param) => {
    try {
      const headerParms = {
        headers: {
          "Content-Type": "application/json",
        },
      };
      const body = { token: param.refreshToken };
      const response = await axios.post(
        "http://localhost:9090/api/auth/login",
        body,
        headerParms
      );
      console.log("Refreshing");
      return {
        isSuccess: true,
        newAuthToken: response.data.accessToken,
        newRefreshToken: response.data.token,
      };
    } catch (error) {
      console.error(error);
      return {
        isSuccess: false,
        newAuthToken: "",
      };
    }
  },
});

export default refresh;

![image](https://github.com/react-auth-kit/react-auth-kit/assets/134660342/028ef545-e28d-49d9-a377-5e01da57f646)

**To Reproduce** \

**Expected behavior** \

**Current behaviour** \
A clear and consise description of what is happening. If possible, give reasoning behind difference in current behaviour and expected behaviour

**Possible solutions** (Optional) \
Give ideas for solving the problem, provide relevant links to additional packages you are mentioning

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Failure Logs**

Please include any relevant log snippets or files here.

**Additional context**

## License

[MIT](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by lukedukeus** [comment]
what does your refresh token look like?

**Comment by kailashkaji** [comment]
refresh token looks like : "3e1601ca-be01-4a60-b613-010aaaf5977a"

**Comment by lukedukeus** [comment]
try modifying your backend to give the client a refresh token that is base64 encoded and also a valid JWT like `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

**Comment by kailashkaji** [comment]
i changed the refresh token and the new token is eyJhbGciOiJIUzI1NiJ9.e30.qjUdsAgU0EcFLe-j--d5OktoNoKeNIF0ZlyNMQU51sM

still same issue its not working
