### ISSUE TITLE
There should be a way to access the token in a plain js file

### ISSUE THREAD

**Issue by adrianjmejias** [react-auth-kit/react-auth-kit#19]
I'm trying to add an interceptor to an axios instance 

```
const laxios = axios.create({ baseURL: APIURL });
laxios.interceptors.request.use((axios) => {
  const authHeader = useAuthHeader();
  const bearer = `Bearer ${authHeader}`;
  axios.headers.authorization = bearer;
});
```
It seems like a reasonable use case to me but I get the following error.

![image](https://user-images.githubusercontent.com/17663584/92977908-3f09d900-f45c-11ea-8cb9-8b65a71d70ce.png)

**Comment by darkmatter18** [comment]
@adrianjmejias React doesn't allow to use hooks outside component. You have to use `useAuthHeader` inside components.

**Comment by adrianjmejias** [comment]
yes, but shouldn't there be a way to access the token in plain js?

**Comment by darkmatter18** [comment]
@adrianjmejias As much as, I read the React docs, I know, there's no way. But if someday I'll find one, I surely implement that.
