### ISSUE TITLE
Tiding the Refresh Token documentation

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#191]
React Auth Kit introduced the Refresh Token feature from `v1.4.3-0`, but the docs are not completed yet.

This issue is for completing the refresh token documentation.

**Comment by shackra** [comment]
Okay, okay, I really need to set some time aside for this one

**Comment by darkmatter18** [comment]
@shackra Any update?

**Comment by shackra** [comment]
> @shackra Any update?

no thus far, sorry for the delay

**Comment by philbert440** [comment]
I would appreciate this too!

**Comment by shackra** [comment]
Okay, I will do a small backend to deploy on Heroku and give life to the documentation. There is no public REST APIs that simulate authentication thus one must be provided.

**Comment by darkmatter18** [comment]
Ok. Please do so.

**Comment by darkmatter18** [comment]
@shackra Updates?

**Comment by shackra** [comment]
> @shackra Updates?
> 

None so far, I'm sorry, I need more time

**Comment by stefanwuthrich** [comment]
is there a chance that this documentation will happen at any time? I would like to help, but I miss understanding how it works so I can't document it. But without I think this really great project will die away.

**Comment by shackra** [comment]
yeah, sorry, I've been busy trying to come with this done

**Comment by ryekerjh** [comment]
> Okay, I will do a small backend to deploy on Heroku and give life to the documentation. There is no public REST APIs that simulate authentication thus one must be provided.

@shackra I can help with getting the API up on Heroku. Do you have any quick thoughts on what you want that mockup REST API to do?

**Comment by shackra** [comment]
> > Okay, I will do a small backend to deploy on Heroku and give life to the documentation. There is no public REST APIs that simulate authentication thus one must be provided.
> 
> @shackra I can help with getting the API up on Heroku. Do you have any quick thoughts on what you want that mockup REST API to do?
> 

something that just return a valid JWT with a refresh JWT should do it
