### ISSUE TITLE
dist/index.js

### ISSUE THREAD

**Issue by philbert440** [react-auth-kit/react-auth-kit#197]
lines 724-725 values and keys are swapped

**Comment by philbert440** [comment]
getCurrentAuthState()

**Comment by darkmatter18** [comment]
Can you please tell me what's happening, in detail. If you can give me an example, please share

**Comment by philbert440** [comment]
getCurrentAuthState().authToken returns 'Bearer' and getCurrentAuthState().authTokenType returns the token.

**Comment by darkmatter18** [comment]
Thanks for the details. Fixing it soon

**Comment by darkmatter18** [comment]
Fixed in 8fc03f5. use V1.4.4 or later
