### ISSUE TITLE
useRefreshToken() is returning the null authState on initial load even when cookies exist

### ISSUE THREAD

**Issue by philbert440** [react-auth-kit/react-auth-kit#198]
**description**
useRefreshToken is returning the default empty/null authState on initial load even when cookies exist

**Steps to reproduce the behavior:**
1. signin gets tokens stores as cookies everything works as logged in
2. refresh the page, gets kicked to login page despite having a valid access token in the _auth_t cookie

**Expected behavior**
use the cookies and return the authState for the logged in user

**Comment by darkmatter18** [comment]
Can you please share with me, your `AuthProvider` and `signin` code

**Comment by philbert440** [comment]
```
        <AuthProvider
          authStorageType = {'cookie'}
          authStorageName={'_auth_t'}
          authTimeStorageName={'_auth_time'}
          refreshTokenName={'_refresh_t'}
          refreshTokenTimeName={'_refresh_time'}
          stateStorageName={'_auth_state'}
          cookieDomain={window.location.hostname}
          cookieSecure={window.location.protocol === "https:"}
        >
          <App />
        </AuthProvider>
```

```
const LoginRegister = () => {
  const classes = useStyles();
  const signIn = useSignIn();
  const [user, setUser] = useState('');
  const [pass, setPass] = useState('');
  const [rem, setRem] = useState(true);
  const [invalid, setInvalid] = useState(false);

  const handleLogin = async (user, pass, setInvalid) => {
    const myHeaders = new Headers();
    myHeaders.append('Content-Type', 'application/x-www-form-urlencoded');

    const urlencoded = new URLSearchParams();
    urlencoded.append('grant_type', 'password');
    urlencoded.append('client_id', `${process.env.REACT_APP_ADAPIFY_CLIENT_ID}`);
    urlencoded.append('client_secret', `${process.env.REACT_APP_ADAPIFY_CLIENT_SECRET}`);
    urlencoded.append('username', `${user}`);
    urlencoded.append('password', `${pass}`);

    const requestOptions = {
      method: 'POST',
      headers: myHeaders,
      body: urlencoded,
      redirect: 'follow',
    };

    const response = await fetch(`${process.env.REACT_APP_ADAPIFY_SITE_URL}/oauth/token`, requestOptions);
    const result = await response.json();
    if (result.access_token) {
      signIn({
        token: result.access_token,
        tokenType: "Bearer",
        expiresIn: 400,
        refreshToken: result.refresh_token,
        refreshTokenExpireIn: 1209600});
    } else {
      setInvalid(true);
    }
    return {
      type: 'LOGIN',
    };
  };
```

**Comment by philbert440** [comment]
I've got a temporary work around in place on my implement that resets the state from the cookies if the refresh token exists. Ideally thought this would be handled in the useRefreshToken() hook...

```
const RefreshComponent = async (user) => {
  const dispatch = useDispatch();
  const refState = useRefreshToken();
  const isAuthenticated = useIsAuthenticated();
  const refToken = Cookies.get('_refresh_t');
  useEffect(() => {
    async function fetchData() {
      if (refToken && refToken !== 'null') {
        if (!refState.getCurrentAuthState().authToken) {
          if (!isAuthenticated()) {
            const authToken = Cookies.get('_auth_t');
            const authTokenType = Cookies.get('_auth_t_type');
            const stateCookie = Cookies.get('_auth_state');
            const refreshToken = Cookies.get('_refresh_t');
            refState.updateUserState(stateCookie);
            refState.updateAuthState(authToken, authTokenType, 400);
            refState.updateRefreshToken(refreshToken, 1209600);
          }
          const myHeaders = new Headers();
          myHeaders.append('Content-Type', 'application/x-www-form-urlencoded');
          const urlencoded = new URLSearchParams();
          urlencoded.append('grant_type', 'refresh_token');
          urlencoded.append('client_id', `${process.env.REACT_APP_ADAPIFY_CLIENT_ID}`);
          urlencoded.append('client_secret', `${process.env.REACT_APP_ADAPIFY_CLIENT_SECRET}`);
          urlencoded.append('refresh_token', refState.getCurrentRefreshToken());

          const requestOptions = {
            method: 'POST',
            headers: myHeaders,
            body: urlencoded,
            redirect: 'follow',
          };

          const response = await fetch(`${process.env.REACT_APP_ADAPIFY_SITE_URL}/oauth/token`, requestOptions);
          if (response.status === 200) {
            const result = await response.json();
            // Setting the auth state
            if (user) { refState.updateUserState(user); }
            refState.updateAuthState(result.access_token, 'Bearer', 400);
            refState.updateRefreshToken(result.refresh_token, 1209600);
          }
          if (response.status !== 200) {
            const err = response;
            return dispatch(utilitiesLoadingErrorAction('AuthIssue', err));
          }
        }
      }
    }
    fetchData();
  }, [dispatch, refState, refToken, user, isAuthenticated]);
}

export {
  RefreshComponent,
};
```
I also had to modify signout a bit to get it to clear out the cookie, I believe this is due to my workaround above

```
                  <MenuItem
                    className={classes.userMenuItem}
                    onClick={() => {
                      Cookies.set('_refresh_t', null)
                      Cookies.set('_auth_t', null)
                      signOut();
                    }}
                  >
                    Logout
                  </MenuItem>
```
Let me know if you need anymore info, or assistance with the changes or testing

**Comment by darkmatter18** [comment]
> I've got a temporary work around in place on my implemention that resets the state from the cookies if the refresh token exists. Ideally thought this would be handled in the useRefreshToken() hook...
> 
> ```
> const RefreshComponent = async (user) => {
>   const dispatch = useDispatch();
>   const refState = useRefreshToken();
>   const isAuthenticated = useIsAuthenticated();
>   const refToken = Cookies.get('_refresh_t');
>   useEffect(() => {
>     async function fetchData() {
>       if (refToken && refToken !== 'null') {
>         if (!refState.getCurrentAuthState().authToken) {
>           if (!isAuthenticated()) {
>             const authToken = Cookies.get('_auth_t');
>             const authTokenType = Cookies.get('_auth_t_type');
>             const stateCookie = Cookies.get('_auth_state');
>             const refreshToken = Cookies.get('_refresh_t');
>             refState.updateUserState(stateCookie);
>             refState.updateAuthState(authToken, authTokenType, 400);
>             refState.updateRefreshToken(refreshToken, 1209600);
>           }
>           const myHeaders = new Headers();
>           myHeaders.append('Content-Type', 'application/x-www-form-urlencoded');
>           const urlencoded = new URLSearchParams();
>           urlencoded.append('grant_type', 'refresh_token');
>           urlencoded.append('client_id', `${process.env.REACT_APP_ADAPIFY_CLIENT_ID}`);
>           urlencoded.append('client_secret', `${process.env.REACT_APP_ADAPIFY_CLIENT_SECRET}`);
>           urlencoded.append('refresh_token', refState.getCurrentRefreshToken());
> 
>           const requestOptions = {
>             method: 'POST',
>             headers: myHeaders,
>             body: urlencoded,
>             redirect: 'follow',
>           };
> 
>           const response = await fetch(`${process.env.REACT_APP_ADAPIFY_SITE_URL}/oauth/token`, requestOptions);
>           if (response.status === 200) {
>             const result = await response.json();
>             // Setting the auth state
>             if (user) { refState.updateUserState(user); }
>             refState.updateAuthState(result.access_token, 'Bearer', 400);
>             refState.updateRefreshToken(result.refresh_token, 1209600);
>           }
>           if (response.status !== 200) {
>             const err = response;
>             return dispatch(utilitiesLoadingErrorAction('AuthIssue', err));
>           }
>         }
>       }
>     }
>     fetchData();
>   }, [dispatch, refState, refToken, user, isAuthenticated]);
> }
> 
> export {
>   RefreshComponent,
> };
> ```
> 
> I also had to modify signout a bit to get it to clear out the cookie, I believe this is due to my workaround above
> 
> ```
>                   <MenuItem
>                     className={classes.userMenuItem}
>                     onClick={() => {
>                       Cookies.set('_refresh_t', null)
>                       Cookies.set('_auth_t', null)
>                       signOut();
>                     }}
>                   >
>                     Logout
>                   </MenuItem>
> ```
> 
> Let me know if you need anymore info, or assistance with the changes or testing

Hey @philbert440, Thanks for your feedback. 

I am not sure, but I think you are altering the current auth states.
Can you use the `getCurrentAuthState()` method to get the auth information and `getCurrentRefreshToken()` to extract the current refresh Token.

Also for sign out use `useSignOut()`, if the problem exists or if you need any help, please let me know. We'll solve the issue together.

Thanks

**Comment by philbert440** [comment]
I've set up a codesandbox, where we can work on it.
https://codesandbox.io/s/nervous-pasteur-ewrfc
username: testuser
password: test@123

**Comment by philbert440** [comment]
it looks like its creating a 2nd set of cookies instead of modifying the existing cookies.

**Comment by darkmatter18** [comment]
I have tested the sandbox, and yea it is creating 2 sets of cookies, but the real fact is I am really not sure, why is this happening.
My test rig doesn't have this problem.
But I noticed that one set has the domain of `ewrfc.csb.io` and another has the `.ewrfc.csb.io`. 

I also tested the whole thing on `localStorage`, but that part is just fine. (Hope it also works for you too 😅)

As the library is dependant on `js-cookie` for cookie related stuffs, so there may be some issue with this library. So after reading their documentation I changed a little bit and released `1.4.5-0`. 

Please test it out, and tell me if the issue is still there, and what differences you found in those 2 sets of cookies. Thanks!

**Comment by philbert440** [comment]
I'll try it this weekend

**Comment by philbert440** [comment]
I was experimenting with localstorage and I'm seeing similar problems there as well, when I manually refresh the localStorage.setItem('_auth_t') and localStorage.setItem('_refresh_t') are still returning null there as well...

**Comment by darkmatter18** [comment]
That's bad to know! I'll try my best to fix the bug. Please give me some time.  I'll give you some updates in a day or two. Thank you.

**Comment by philbert440** [comment]
I found the issue, apparently I wasn't using JSON.stringify() when storing the user object to '_auth_state'. Once I fixed that, everything started working as intended. Thanks so much for your assistance along the way, closing the issue.
