### ISSUE TITLE
Cookies are not being stored

### ISSUE THREAD

**Issue by dd8888** [react-auth-kit/react-auth-kit#25]
Hey, I'm trying to implement the useIsAuthenticated() method like this: 

`const isAuthenticated = useIsAuthenticated();
    if (isAuthenticated()) {
    return (
      <Switch>
        <Route path="/perfil" component={Perfil}></Route>
        <Redirect to="/perfil" />
      </Switch>
    );
  } else {
    return (
      <Switch>
        <Route path="/login" component={Index} />
        <Redirect to="/login" />
      </Switch>
    );
  }
};`

The login is working, I get redirected to the "perfil" page. The problem is that if I reload the page, I get redirected to the login page again and also I get logged out.

**Comment by dd8888** [comment]
I just tried using `authStorageType="localstorage"` and it works, but if I try it with cookies it doesn't.

**Comment by dd8888** [comment]
I'm using `AuthProvider` like this: 
`<AuthProvider
      authStorageType={'cookie'}
      authCookieName={'_a'}
      authTimeCookieName={'_at'}
      stateCookieName={'_s'}
      cookieDomain={window.location.hostname}
      cookieSecure={window.location.protocol === 'http:'}
    >`
And it seems like cookies are not being stored.

**Comment by darkmatter18** [comment]
@dd8888 Thanks for your issue. I figured out that the docs are actually `deprecated`. 
Please use 

```jsx
<AuthProvider authStorageType = {'cookie'}
                  authStorageName={'_auth_t'}
                  authTimeStorageName={'_auth_time'}
                  stateStorageName={'_auth_state'}
                  cookieDomain={window.location.hostname}
                  cookieSecure={window.location.protocol === "https:"}>
        ///
    </AuthProvider>
```

as your AuthProvider. I hope this will fix the issue. Thanks a lot

**Comment by dd8888** [comment]
I just tried that and same error, don't know why but cookies are not being stored. That's why if I refresh the page I get redirected to the login page.

**Comment by darkmatter18** [comment]
@dd8888 Let me check, and I'll try to fix the error

**Comment by dd8888** [comment]
How should I set the cookieDomain while working on localhost? Maybe that's the problem.

**Comment by darkmatter18** [comment]
Hey, @dd8888 I just fixed the issue in version 1.2.0 Please install that, and check if that working

**Comment by dd8888** [comment]
Same problem. Seems like storing cookies while working on localhost is a known issue.

**Comment by darkmatter18** [comment]
for cookieDomain, use `cookieDomain={window.location.hostname}`

**Comment by dd8888** [comment]
Same problem. If you need anything else just @ me.

**Comment by darkmatter18** [comment]
@dd8888 Please let me see your `AuthProvider` with it's props

**Comment by dd8888** [comment]
`<AuthProvider
      authStorageType={'cookie'}
      authStorageName={'_auth_t'}
      authTimeStorageName={'_auth_time'}
      stateStorageName={'_auth_state'}
      cookieDomain={window.location.hostname}
      cookieSecure={window.location.protocol === 'http:'}
    >
      <Router>
        <Routes />
      </Router>
    </AuthProvider>`

It's the same, I only changed "https" to "http". I have been testing this: I create a cookie manually named "a". If I rename the cookie "a" with the name from the cookie that it's supposed to be created from the library and refresh, the cookie is removed. But if I create the cookie "a" again and rename it "b", it stays there. Weird.

**Comment by darkmatter18** [comment]
@dd8888 Hey, I tested many times so far and got nothing. So I think your codebase has some issues. I just created an Example repo, https://github.com/react-auth-kit/Example . So please check this up and then tell me, if you have any problem.

**Comment by dd8888** [comment]
Ha! It worked! I think that the main problem was setting the `window.location.protocol` to http instead of https (even tho localhost is http right?) Anyway great job and sorry for the inconvenience.

**Comment by FabianoFGomes** [comment]
@darkmatter18 and @dd8888
Actually I think this problem is related when 'tokenType' is empty field.
If you remove the 'tokenType' field when using useSignIn -> signIn or set 'bearer (e.g.)' will works well. If you supply the blank 'tokenType' the problem keeps happening.
