### ISSUE TITLE
useAuthUser doesn't return an object

### ISSUE THREAD

**Issue by jnthnk** [react-auth-kit/react-auth-kit#334]
The hook useAuthUser doesn't return an object as described in the [docs](https://authkit.arkadip.me/authdata/).

It returns a function that I have to run in order to get the object.

That is the desired functionality?

Thanks.

**Comment by PatzMatias** [comment]
Yes, I just used it that way. The docs didn't tell that.. If you're using TS you might also face a TS problem about accessing properties the returned object because the inferred object is a blank object.

**Comment by darkmatter18** [comment]
@jnthnk Yea, That's the desired functionality. I created that to match with other Hooks, if you notice, all hooks have the same `function inside a function property.
But yeah, the docs are wrong. I'll change that soon. If you guys can, then please do.
@PatzMatias Saw your PR, will marge soon

**Comment by darkmatter18** [comment]
Docs fixed on 1.4.8
