### ISSUE TITLE
Hook to update local state after sign in

### ISSUE THREAD

**Issue by codejeet** [react-auth-kit/react-auth-kit#45]
**Is your feature request related to a problem? Please describe.**
Sometimes it is useful to have user state that is not sent on sign in, but rather at the users request on another page. However, it doesn't seem possible to globally update new values after the useSignIn() function is called, unless you just call the useSignIn() hook with the current values + updated ones. 

**Describe the solution you'd like**
Some kind of hook where I can provide a value to store to localstorage/cookies. 

**Describe alternatives you've considered**

I'm doing this at the moment as a hack

```
signIn({
      token: authHeader().toString().split(' ')[1],
      expiresIn: 10080,
      tokenType: 'Bearer',
      authState: Object.assign({ newVal: 'newVal' }, authUser()),
    })
```

**Comment by darkmatter18** [comment]
@codejeet Can you please explain, why you think this feature is needed?

**Comment by codejeet** [comment]
My login flow is oauth to create a token, then redirect to another form page to fill in more user information. I call useSignIn after the oauth login, then I have to call useSignIn again after the form submission with new and old values in order to update the user state to the new values. This kind of authentication flow is not uncommon, and we often want detailed user state to persist across pages.
