### ISSUE TITLE
On page refresh it's deleting cookie

### ISSUE THREAD

**Issue by prashant19** [react-auth-kit/react-auth-kit#473]
**Describe the bug**
On page refresh it's deleting my cookie and not able to use privateroute and Authentication.

Node version :14.17.1
React: "^17.0.2",
React-auth-kit": "^1.4.14",

**Comment by darkmatter18** [comment]
Hey, It's so sorry so here  such an issue, please send me your routers file. where you put your BrowerRouter.
Also please check the standard example https://github.com/react-auth-kit/react-auth-kit/tree/master/examples/create-react-app

**Comment by prashant19** [comment]
Hi,

We got the same issue in your create-react-app example. After login when we reload the page the cookie is getting deleted.

The expected behaviour should be once you logged-in and cookie is valid so we should be able to access all the secure pages, either by reloading page window or navigating though links.

Also we found the js-cookie dependency issue in create-react-app example, to resolve the we manually installed the js-cookie Package.

Please do let me know if there is any understanding gaps.

Thanks,
Prashant

**Comment by darkmatter18** [comment]
I got the issue. Fixing the issue soon

**Comment by darkmatter18** [comment]
Please update `react-auth-kit` to `1.4.16`. It will fix the issue. Thanks

**Comment by prashant19** [comment]
I m still facing the same issue with   "react-auth-kit": "^1.4.16".
The expected behaviour should be once you logged-in and cookie is valid so we should be able to access all the secure pages, either by reloading page window or navigating though links.

**Comment by darkmatter18** [comment]
I tested the create-react-app example, and that worked just fine. So I am not sure, what's happening with your project. See the example, if you missed something. so the other side, I am also trying to hunt more bugs. if exists. Thanks

**Comment by wahid-adapta** [comment]
I'm having this issue again in 2.5.0
