### ISSUE TITLE
Make a developer guideline for docs

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#56]
- Make a contribution procedure for documentation.
- Create the guideline on [CONTRIBUTING.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md).
- Only change the `CONTRIBUTING.md`

**Guideline:**

- The docs are based on [Mkdocs](https://www.mkdocs.org/)
- The docs use the [Mkdocs Material Theme](https://squidfunk.github.io/mkdocs-material)

**Comment by dotslash21** [comment]
@darkmatter18, I'll work on this one.

**Comment by darkmatter18** [comment]
@dotslash21 Assigned!! Go for it
