### ISSUE TITLE
Add Unit Test Case for TokenObject.ts

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#577]
> This issue is a part of  `Hacktoberfest 2021`. All developers are welcome

## What to do
- The job is to add unit test cases for the `TokenObject.ts` file.
- There are 2 functions
    1. initialToken()
    2. syneTokens()
Adding test cases for these 2 functions should cover everything.
If it doesn't cover something, don't panic, simply make a PR, we will work on that.

## Technology
- Programming Language uses: `TypeScript`
- For testing, the library used `Jest`. Jest should be enough to write unit test.

## Where to do
- Add the file inside `src/__tests__`  directory
- Name the file as `TokenObject.test.ts`

## Important ‼
**_Make sure your commits follow the  Conventional commit https://www.conventionalcommits.org/en/v1.0.0/, or it'll break the CI._**

_** The best way to avoid the linting issue in CI is always to set up your dev env with `npm install`. It will set husky and list stages._

> ***Need help?***
***Feel free to contact me @ [in2arkadipb13@gmail.com](mailto:in2arkadipb13@gmail.com)***

**Comment by tumit** [comment]
Can I take this issue ?
