### ISSUE TITLE
Add unit test for actions.ts and reducers.ts

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#578]
> This issue is a part of  `Hacktoberfest 2021`. All developers are welcome

## What to do
- The job is to **_add unit test cases_** for the `/src/utils/actions.ts` and `/src/utils/reducers.ts` files.
- You have to make a react component inside the test file to simulate the test.
- Make sure that you can at least achieve **_60%_** coverage.

## Technology
- Programming Language uses: `TypeScript`
- For testing, the library used `Jest`.
- For React component simulation, we library uses `testing-library/react`

## Where to do
- Add the file inside `src/__tests__/utils`  directory
- Name the files should be `actions.test.ts` and `reducers.test.ts`

> ***Need help?***
***Feel free to contact me @ [in2arkadipb13@gmail.com](mailto:in2arkadipb13@gmail.com)***

**Comment by atrievel** [comment]
@darkmatter18 - I'd love to take this one if it is still available, thnaks!
