### ISSUE TITLE
Add commit lint guideline in contributing.md

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#588]
> This issue is a part of `Hacktoberfest 2021`

Our library uses Conventional commit https://www.conventionalcommits.org/en/v1.0.0/ to make sure that the commit messages stay perfect.

## What to do
- The Job of this issue is to refactor the `CONTRIBUTING.md` file
- Add a section as `Conventional Commit`
- Under the section add all necessary rules in an unordered list.
- You'll get any library defined rule in `commitlint.config.js`

## Where to do
- Update only the `CONTRIBUTING.md` etc.

## Before you contribute
- Make sure to read the [README.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/README.md) file.
- Make sure you read the [CONTRIBUTING.MD](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md) file.

## Important ‼
**_Make sure your commits follow the  Conventional commit https://www.conventionalcommits.org/en/v1.0.0/, or it'll break the CI._**

_** The best way to avoid the linting issue in CI is always to set up your dev env with `npm install`. It will set husky and list stages._

> ***Need help?***
***Feel free to contact me @ [in2arkadipb13@gmail.com](mailto:in2arkadipb13@gmail.com)***

**Comment by DarrylBrooks97** [comment]
Opened a PR here #593 🚀
