### ISSUE TITLE
`signIn` hook sets `expiresIn` for both `token` and `refreshToken`

### ISSUE THREAD

**Issue by scr2em** [react-auth-kit/react-auth-kit#589]
**Describe the bug**
while using `authType = 'cookie'`
`signIn` hook set `expiresIn` for both `token` and `refreshToken` and totally neglecting `refreshTokenExpireIn`

version used : 1.4.18
              
**To Reproduce**
1- use  
```
signIn({
        token,
        expiresIn: 43200 * 1         /*30 days*/,
        refreshToken,
        refreshTokenExpireIn: 43200 * 3      /*90 days*/,
        tokenType: 'Bearer',
        authState: user,
 })
```
2- check the cookies expiration date 
3- all cookies have the same expiration date 

**Expected behavior**
token cookie should expires in 1 month
refreshToken cookie should expires in 3 months 

**Screenshots**
![image](https://user-images.githubusercontent.com/4671486/136009138-2a5d9ace-06bf-4ef3-8a25-b09145a7afb8.png)

as indicated, the `_refresh` cookie expiration date should be the value of `_refresh_time`

**Additional context**
I noticed in your `TokenObject.ts` 

```
 if (this.isUsingRefreshToken && !!this.refreshTokenName &&
      !!refreshToken) {
      Cookies.set(this.refreshTokenName, refreshToken, {
        expires: expiresAt,
        domain: this.cookieDomain,
        secure: this.cookieSecure,
      });
    }
 ```

you setting the expires property to `expiresAt` which comes from `expiresIn` in signIn function 
shouldn't it be `refreshTokenExpiresAt` ?

**Comment by darkmatter18** [comment]
@scr2em I know that there is a bug in the Refresh Token feature. I'm working on it. Sorry for your inconvenience. I'll try to fix it as soon as possible.
