### ISSUE TITLE
Write unit test cases for PrivateRoute.ts

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#595]
> This issue is a part of  `Hacktoberfest 2021`. All developers are welcome

## What to do
- The job is to **_add unit test cases_** for the `/src/PrivateRoute.tsx` file
- Make sure that you can at least achieve **_60%_** coverage.

## Technology
- Programming Language uses: `TypeScript`
- For testing, the library used `Jest`.
- For React component simulation, we library uses `testing-library/react`

## Where to do
- Add the file inside `src/__tests__`  directory
- Name the files should be `PrivateRoute.test.tsx`

## Before you contribute
- Make sure to read the [README.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/README.md) file.
- Make sure you read the [CONTRIBUTING.MD](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md) file.

## Important ‼
**_Make sure your commits follow the  Conventional commit https://www.conventionalcommits.org/en/v1.0.0/, or it'll break the CI._**

_** The best way to avoid the linting issue in CI is always to set up your dev env with `npm install`. It will set husky and list stages._

> ***Need help?***
***Feel free to contact me @ [in2arkadipb13@gmail.com](mailto:in2arkadipb13@gmail.com)***

**Comment by sitek94** [comment]
Hey there 👋

I think I could find some time over this weekend to take a look at that, is it okay with you? :)

**Comment by darkmatter18** [comment]
> Hey there 👋
> 
> I think I could find some time over this weekend to take a look at that, is it okay with you? :)

Yea Sure
