### ISSUE TITLE
Seasion cookies

### ISSUE THREAD

**Issue by scr2em** [react-auth-kit/react-auth-kit#597]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a `remember me` functionality and needs to store the cookies as session cookies (has no expiration date and automatically deleted when the user close the tab).

**Describe the solution you'd like**
we should have an option to put and expiration date (normal cookie) or not ( session cookie) 
I forked the repo and I will try to implement it, just made this request in case I fail.

**Describe alternatives you've considered**
I used `addEventListener('beforeunload")` to delete all cookies 

**Additional context**
I feel like this feature should be built-in instead of `addEventListener`

**Comment by darkmatter18** [comment]
I removed this from 1.5 update. 
@scr2em You can work on it freely. This feature will be taken into consideration in the next release.
