### ISSUE TITLE
Write unit test cases for AuthProvider

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#608]
> This issue is a part of  `Hacktoberfest 2021`. All developers are welcome

## What to do
- The job is to **_add assertion statements in unit test cases_** for the `/src/AuthProvider.tsx` file
**_- There are already test cases written. But we need to have more assertion statements._**

## Technology
- Programming Language uses: `TypeScript`
- For testing, the library used `Jest`.
- For React component simulation, we library uses `testing-library/react`

## Where to do
- Add the file inside `src/__tests__`  directory
- Name the files should be `PrivateRoute.test.tsx`

## Before you contribute
- Make sure to read the [README.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/README.md) file.
- Make sure you read the [CONTRIBUTING.MD](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md) file.

## Important ‼
**_Make sure your commits follow the  Conventional commit https://www.conventionalcommits.org/en/v1.0.0/, or it'll break the CI._**

_** The best way to avoid the linting issue in CI is always to set up your dev env with `npm install`. It will set husky and list stages._

> ***Need help?***
***Feel free to contact me @ [in2arkadipb13@gmail.com](mailto:in2arkadipb13@gmail.com)***

**Comment by ok524** [comment]
I would like to take this!
May I have your clarification on the file I should work on is `src/__tests__/AuthProvider.test.tsx`, am I right?

I am going to add an assertion using `expect()` below `// TODO: assertion statements needed` and insert a `<AuthContextConsumer />` inside the `render()` to retrieve value of `authState.isSignIn`.
