### ISSUE TITLE
Demo code in docs not working

### ISSUE THREAD

**Issue by dotslash21** [react-auth-kit/react-auth-kit#63]
**Describe the bug**
The demo code for **Auth User Data** and **Auth Header** hooks are not working. After some tinkering, I found out that both the `useAuthUser` and `useAuthHeader` returns a function, and on calling those functions we get the actual data we need.

**To Reproduce**
1) Run the demo code for the hooks method.

**Expected behavior**
I'm not sure about this either the documentation or the implementation has the issue, needs clarification from @darkmatter18. 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Chrome 85.0.4183.121
 - Version 1.2.2

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
None

**Comment by darkmatter18** [comment]
@dotslash21 `useAuthUser` and `useAuthHeader` are initially created in this manner with a signature of `useAuthHeader(): () => (string)` and ` useAuthUser(): () => object | null`. 
I am thinking to change them to `useAuthHeader(): string` and ` useAuthUser(): object | null`, if you can then please do, else I'll do them later. Thanks a lot

**Comment by dotslash21** [comment]
@darkmatter18 I'll see if I can make this change. BTW awesome work on creating this project, saved a lot of time for me.

**Comment by darkmatter18** [comment]
@dotslash21 Thanks a lot for your kind review
