### ISSUE TITLE
AuthProvider refresh callback is called multiple times per second

### ISSUE THREAD

**Issue by xterr** [react-auth-kit/react-auth-kit#643]
**Describe the bug**
AuthProvider refresh callback is called multiple times per second

**To Reproduce**
1. Set refresh property using createRefresh method
2. return the refresh object populated using existing values, except the `*expiresIn` properties which can be set to 10 (minutes), for example
3. add a console.log just before the return of the refresh object
4. + observe in Application > localstorage that the properties containing the dates are getting refreshed multiple times per second

**Expected behavior**
The callback shouldn't be called multiple times per second

**Desktop (please complete the following information):**
 - OS: OSx
 - Browser Chrome
 - Version 92.0.4515

**Comment by darkmatter18** [comment]
Can you show me your codebase, especially the createRefresh Function

**Comment by vlev322** [comment]
@darkmatter18 Hello, any updates about this issue?
