### ISSUE TITLE
Complete documentation for functions for hooks files

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#67]
- This issue has no `code change`
- You only have to write `documentations`
- `Documentations` should have the standard of [JsDoc](https://jsdoc.app/)
- Don't add `param types` and `return types`, as we are using typescript
- Only Add documentation for `useAuth.ts`, `useAuthHeader.ts`, `useAuthUser.ts`, `useIsAuthenticated.ts`, `useSignIn.ts` and `useSignOut.ts`

Please read the [CONTRIBUTING.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md)

**Comment by Hardik0307** [comment]
@darkmatter18, Like to contribute!

Assign me.

**Comment by darkmatter18** [comment]
@Hardik0307 Assigning to you. Go for it
