### ISSUE TITLE
Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

### ISSUE THREAD

**Issue by reovilsayed** [react-auth-kit/react-auth-kit#683]
When I was trying to use useAuthHeader I get this error.  Can you please tell the solution?
Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

**Comment by Sergeant227** [comment]
Because you're trying to display the function itself. You have to call it and then display the result.
