### ISSUE TITLE
Complete documentation for functions for Higher Order Component files

### ISSUE THREAD

**Issue by darkmatter18** [react-auth-kit/react-auth-kit#69]
- This issue has no `code change`
- You only have to write `documentations`
- `Documentations` should have the standard of [JsDoc](https://jsdoc.app/)
- Don't add `param types` and `return types`, as we are using typescript
- Only Add documentation for `withAuthHeader.tsx`, `withAuthUser.tsx`, `withIsAuthenticated.tsx`, `withSignIn.tsx` and `withSignOut.tsx`

Please read the [CONTRIBUTING.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/CONTRIBUTING.md)

**Comment by Hardik0307** [comment]
@darkmatter18 same as #67 

Want to work on this.

**Comment by darkmatter18** [comment]
@Hardik0307 Go for it
