### ISSUE TITLE
Cannot update a component (`AuthProvider`) while rendering a different component (`RequireAuth`).

### ISSUE THREAD

**Issue by boyboi86** [react-auth-kit/react-auth-kit#916]
**Describe the bug**

I am currently trying out react 18 & redux toolkit

So I have 3 files namely index.route, login.page & app.

Within the app file I placed "AuthProvider" as advice however because I have too many routes so I created another file call "index.route" where "RequiredAuth" resides. 

Lastly my login & logout component are coming from "login.page" to "app.header" & "index.route"

**The module works for sure** but I kept getting the below messages whenever I logout

![image](https://user-images.githubusercontent.com/12681196/165452039-da4bfde0-669e-4e44-a896-9f2942e95c26.png)
![image](https://user-images.githubusercontent.com/12681196/165452409-5cb39638-53c2-47c7-8a98-eefeaefc2bdb.png)

My folder structure is as below:

![image](https://user-images.githubusercontent.com/12681196/165451790-05486687-a84d-4529-ab9b-e2e62ca0def9.png)

My logout component is as below:

```
export const LogOutComponent = () => {
  const signOut = useSignOut();
  const isAuthenticated = useIsAuthenticated();
  console.log("logout",isAuthenticated());


  return <button onClick={() => signOut()}><LogoutIcon/></button>;
};
```

**Expected behavior**
console.log should always be clean.

I would greatly appreciate for any advice. Thank you.

**Comment by emrahaydemir** [comment]
same here. i installed your example project and im getting same error. https://codesandbox.io/s/winter-frog-idzrfm?file=/src/App.js

**Comment by darkmatter18** [comment]
@emrahaydemir Thanks for the Example. I'll surely look into this issue imediately

**Comment by boyboi86** [comment]
Dear @darkmatter18 @emrahaydemir  , apologies for the late reply. This is NOT A BUG.

After I tried testing a few times, this is how it should work out. If you cannot "signout" while you are still in secure route, it will give you the above error message. So what I did was i useNavigate("/") to  root directory then invoke signOut().

It works for me. No more error, cause no need to further render etc.

however before any sign in, if you try to "brute force" by typing in the route. It will prompt error message. (See below)

![image](https://user-images.githubusercontent.com/12681196/170855617-8cfc6c96-df1a-46b3-809d-c455e67649e0.png)

**Comment by eliawk** [comment]
@darkmatter18 I've this issue too!
if I'm not logged in and I try to navigate to a protect page I will be redirect to the login page but in the console I get the same error as @boyboi86 

![Schermata 2023-01-12 alle 10 32 28](https://user-images.githubusercontent.com/362016/212030408-1eb4c304-72f0-47ce-8582-31330a6a94c2.png)
